#if UNITY_EDITOR
using UnityEngine; using UnityEditor;
public static class LiquidRingWavesFXBuilder{
 const string R="Assets/LiquidRingWavesFX",G=R+"/Generated";
 [InitializeOnLoadMethod] static void Auto(){EditorApplication.delayCall+=Build;}
 [MenuItem("Tools/Liquid Ring Waves FX/Create or Refresh Prefab")]
 public static void Build(){if(!AssetDatabase.IsValidFolder(R))return;if(!AssetDatabase.IsValidFolder(G))AssetDatabase.CreateFolder(R,"Generated");
  var ring=Mat(G+"/M_Ring.mat",R+"/Textures/T_LiquidRing.png",true);var rip=Mat(G+"/M_Ripple.mat",R+"/Textures/T_WaterRipples.png",true);var drop=Mat(G+"/M_Drop.mat",R+"/Textures/T_WaterDroplet.png",false);var sp=Mat(G+"/M_Sparkle.mat",R+"/Textures/T_WaterSparkle.png",true);
  var root=new GameObject("LiquidRingWavesFX"); Ring(root.transform,ring); Ripples(root.transform,rip); Drops(root.transform,drop,"Circular_Wave_Droplets",14,.08f,.22f); Drops(root.transform,drop,"Small_Splash_Droplets",9,.18f,.42f); Bubbles(root.transform,drop); Sparkles(root.transform,sp);
  string p=G+"/LiquidRingWavesFX.prefab";var old=AssetDatabase.LoadAssetAtPath<GameObject>(p);if(old)AssetDatabase.DeleteAsset(p);PrefabUtility.SaveAsPrefabAsset(root,p);Object.DestroyImmediate(root);AssetDatabase.SaveAssets();AssetDatabase.Refresh();Debug.Log("Created "+p);}
 static Material Mat(string p,string t,bool add){Shader s=Shader.Find("Universal Render Pipeline/Particles/Unlit");if(!s)s=Shader.Find("Particles/Standard Unlit");if(!s)s=Shader.Find(add?"Legacy Shaders/Particles/Additive":"Legacy Shaders/Particles/Alpha Blended");var m=AssetDatabase.LoadAssetAtPath<Material>(p);if(!m){m=new Material(s);AssetDatabase.CreateAsset(m,p);}else m.shader=s;var x=AssetDatabase.LoadAssetAtPath<Texture2D>(t);if(m.HasProperty("_BaseMap"))m.SetTexture("_BaseMap",x);if(m.HasProperty("_MainTex"))m.SetTexture("_MainTex",x);m.renderQueue=3000;return m;}
 static void Ring(Transform p,Material m){var g=GameObject.CreatePrimitive(PrimitiveType.Quad);g.name="Liquid_Glowing_Ring";g.transform.SetParent(p,false);g.transform.localRotation=Quaternion.Euler(90,0,0);g.transform.localScale=Vector3.one*2.2f;Object.DestroyImmediate(g.GetComponent<Collider>());g.GetComponent<MeshRenderer>().sharedMaterial=m;g.AddComponent<LiquidRingRotator>();}
 static ParticleSystem PS(string n,Transform p,Material m){var g=new GameObject(n);g.transform.SetParent(p,false);var ps=g.AddComponent<ParticleSystem>();var a=ps.main;a.loop=true;a.playOnAwake=true;a.simulationSpace=ParticleSystemSimulationSpace.Local;var r=g.GetComponent<ParticleSystemRenderer>();r.renderMode=ParticleSystemRenderMode.Billboard;r.material=m;return ps;}
 static void Ripples(Transform p,Material m){var ps=PS("Expanding_Water_Ripples",p,m);var a=ps.main;a.startLifetime=2.2f;a.startSpeed=0;a.startSize=.55f;a.maxParticles=10;var e=ps.emission;e.rateOverTime=.9f;var sh=ps.shape;sh.enabled=false;var z=ps.sizeOverLifetime;z.enabled=true;z.size=new ParticleSystem.MinMaxCurve(1,new AnimationCurve(new Keyframe(0,.45f),new Keyframe(1,2.4f)));}
 static void Drops(Transform p,Material m,string n,float rate,float lo,float hi){var ps=PS(n,p,m);var a=ps.main;a.startLifetime=new ParticleSystem.MinMaxCurve(1.1f,2f);a.startSpeed=new ParticleSystem.MinMaxCurve(lo,hi);a.startSize=new ParticleSystem.MinMaxCurve(.015f,.05f);a.maxParticles=100;var e=ps.emission;e.rateOverTime=rate;var sh=ps.shape;sh.shapeType=ParticleSystemShapeType.Circle;sh.radius=.92f;sh.radiusThickness=.08f;var v=ps.velocityOverLifetime;v.enabled=true;v.y=new ParticleSystem.MinMaxCurve(.05f,.2f);var no=ps.noise;no.enabled=true;no.strength=.035f;no.frequency=.45f;}
 static void Bubbles(Transform p,Material m){var ps=PS("Rising_Bubbles",p,m);var a=ps.main;a.startLifetime=new ParticleSystem.MinMaxCurve(1.8f,3.2f);a.startSpeed=.04f;a.startSize=new ParticleSystem.MinMaxCurve(.012f,.04f);var e=ps.emission;e.rateOverTime=7;var sh=ps.shape;sh.shapeType=ParticleSystemShapeType.Circle;sh.radius=.55f;var v=ps.velocityOverLifetime;v.enabled=true;v.y=new ParticleSystem.MinMaxCurve(.1f,.24f);}
 static void Sparkles(Transform p,Material m){var ps=PS("Water_Sparkle_Motes",p,m);var a=ps.main;a.startLifetime=new ParticleSystem.MinMaxCurve(.7f,1.8f);a.startSpeed=.03f;a.startSize=new ParticleSystem.MinMaxCurve(.008f,.028f);var e=ps.emission;e.rateOverTime=13;var sh=ps.shape;sh.shapeType=ParticleSystemShapeType.Circle;sh.radius=1.05f;sh.radiusThickness=.12f;}
}
#endif